apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: host-route
spec:
  routes:
    - match: Host(`buffer.localhost`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: auth-server
          port: 80
      middlewares:
        - name: limit
